CC=javac

all: compileTonals compileWavFile
	$(CC) ./MyCode/*.java

compileTonals:
	$(CC) ./tonals/*.java

compileWavFile:
	$(CC) ./WavFile/*.java
clean:
	rm ./MyCode/*.class
	rm ./WavFile/*.class
	rm ./tonals/*.class


