@startuml

title __WAVFILE's Class Diagram__\n

  namespace WavFile {
    class WavFile.ReadExample {
        {static} + main()
    }
  }
  

  namespace WavFile {
    class WavFile.WavFile {
        {static} - BUFFER_SIZE : int
        {static} - DATA_CHUNK_ID : int
        {static} - FMT_CHUNK_ID : int
        {static} - RIFF_CHUNK_ID : int
        {static} - RIFF_TYPE_ID : int
        - blockAlign : int
        - buffer : byte[]
        - bufferPointer : int
        - bytesPerSample : int
        - bytesRead : int
        - file : File
        - floatOffset : double
        - floatScale : double
        - frameCounter : long
        - iStream : FileInputStream
        - numChannels : int
        - numFrames : long
        - oStream : FileOutputStream
        - sampleRate : long
        - validBits : int
        - wordAlignAdjust : boolean
        + close()
        + display()
        + display()
        + getFramesRemaining()
        + getNumChannels()
        + getNumFrames()
        + getSampleRate()
        + getValidBits()
        {static} + main()
        {static} + newWavFile()
        {static} + openWavFile()
        + readFrames()
        + readFrames()
        + readFrames()
        + readFrames()
        + readFrames()
        + readFrames()
        + readFrames()
        + readFrames()
        + readFrames()
        + readFrames()
        + readFrames()
        + readFrames()
        + writeFrames()
        + writeFrames()
        + writeFrames()
        + writeFrames()
        + writeFrames()
        + writeFrames()
        + writeFrames()
        + writeFrames()
        + writeFrames()
        + writeFrames()
        + writeFrames()
        + writeFrames()
        - WavFile()
        {static} - getLE()
        {static} - putLE()
        - readSample()
        - writeSample()
    }
  }
  

  namespace WavFile {
    enum IOState {
      CLOSED
      READING
      WRITING
    }
  }
  

  namespace WavFile {
    class WavFile.WavFileException {
        + WavFileException()
        + WavFileException()
        + WavFileException()
        + WavFileException()
    }
  }
  

  namespace WavFile {
    class WavFile.WriteExample {
        {static} + main()
    }
  }
  

  WavFile.WavFile o-- WavFile.WavFile.IOState : ioState
  WavFile.WavFile +-down- WavFile.WavFile.IOState


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
